;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "pr-commit-check-skill")
(def path ".")
(def version "0.1.19")
(def tag "0.1.19")
(def generated-at "2020-08-05T18:13:55Z")
