;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "pr-commit-check-skill")
(def path ".")
(def version "0.1.25")
(def tag "0.1.25")
(def generated-at "2020-08-20T20:49:29Z")
