;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "pr-commit-check-skill")
(def path ".")
(def version "0.1.26")
(def tag "0.1.26")
(def generated-at "2020-10-27T00:44:15Z")
